version: '3.7'

services:
  broker:
    container_name: locksense-broker
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt-broker/passwd:/etc/mosquitto/passwd
      - /mosquitto/data:/mosquitto/data
      - /mosquitto/log:/mosquitto/log
