FROM python:3.9

COPY /storage/image-requirements.txt /requirements.txt
COPY /entrypoints/entrypoint-photos.sh /entrypoint.sh

RUN pip3 install --upgrade pip && \
      pip3 install -r requirements.txt

ENTRYPOINT ["./entrypoint.sh"]

CMD ["python3"]

